export const ALL_CURRENCIES = [
  { value: "AED", text: "UAE dirham" },
  { value: "AFN", text: "Afghan afghani" },
  { value: "ALL", text: "Albanian lek" },
  { value: "AMD", text: "Armenian dram" },
  { value: "ANG", text: "Netherlands Antillean gulden" },
  { value: "AOA", text: "Angolan kwanza" },
  { value: "ARS", text: "Argentine peso" },
  { value: "AUD", text: "Australian dollar" },
  { value: "AWG", text: "Aruban florin" },
  { value: "AZN", text: "Azerbaijani manat" },
  {
    value: "BAM",
    text: "Bosnia and Herzegovina konvertibilna marka",
  },
  { value: "BBD", text: "Barbadian dollar" },
  { value: "BDT", text: "Bangladeshi taka" },
  { value: "BGN", text: "Bulgarian lev" },
  { value: "BHD", text: "Bahraini dinar" },
  { value: "BIF", text: "Burundi franc" },
  { value: "BMD", text: "Bermudian dollar" },
  { value: "BND", text: "Brunei dollar" },
  { value: "BOB", text: "Bolivian boliviano" },
  { value: "BRL", text: "Brazilian real" },
  { value: "BSD", text: "Bahamian dollar" },
  { value: "BTN", text: "Bhutanese ngultrum" },
  { value: "BWP", text: "Botswana pula" },
  { value: "BYR", text: "Belarusian ruble" },
  { value: "BZD", text: "Belize dollar" },
  { value: "CAD", text: "Canadian dollar" },
  { value: "CDF", text: "Congolese franc" },
  { value: "CHF", text: "Swiss franc" },
  { value: "CLP", text: "Chilean peso" },
  { value: "CNY", text: "Chinese/Yuan renminbi" },
  { value: "COP", text: "Colombian peso" },
  { value: "CRC", text: "Costa Rican colon" },
  { value: "CUC", text: "Cuban peso" },
  { value: "CVE", text: "Cape Verdean escudo" },
  { value: "CZK", text: "Czech koruna" },
  { value: "DJF", text: "Djiboutian franc" },
  { value: "DKK", text: "Danish krone" },
  { value: "DOP", text: "Dominican peso" },
  { value: "DZD", text: "Algerian dinar" },
  { value: "EEK", text: "Estonian kroon" },
  { value: "EGP", text: "Egyptian pound" },
  { value: "ERN", text: "Eritrean nakfa" },
  { value: "ETB", text: "Ethiopian birr" },
  { value: "EUR", text: "European Euro" },
  { value: "FJD", text: "Fijian dollar" },
  { value: "FKP", text: "Falkland Islands pound" },
  { value: "GBP", text: "British pound" },
  { value: "GEL", text: "Georgian lari" },
  { value: "GHS", text: "Ghanaian cedi" },
  { value: "GIP", text: "Gibraltar pound" },
  { value: "GMD", text: "Gambian dalasi" },
  { value: "GNF", text: "Guinean franc" },
  { value: "GQE", text: "Central African CFA franc" },
  { value: "GTQ", text: "Guatemalan quetzal" },
  { value: "GYD", text: "Guyanese dollar" },
  { value: "HKD", text: "Hong Kong dollar" },
  { value: "HNL", text: "Honduran lempira" },
  { value: "HRK", text: "Croatian kuna" },
  { value: "HTG", text: "Haitian gourde" },
  { value: "HUF", text: "Hungarian forint" },
  { value: "IDR", text: "Indonesian rupiah" },
  { value: "ILS", text: "Israeli new sheqel" },
  { value: "INR", text: "Indian rupee" },
  { value: "IQD", text: "Iraqi dinar" },
  { value: "IRR", text: "Iranian rial" },
  { value: "ISK", text: "Icelandic kr\u00f3na" },
  { value: "JMD", text: "Jamaican dollar" },
  { value: "JOD", text: "Jordanian dinar" },
  { value: "JPY", text: "Japanese yen" },
  { value: "KES", text: "Kenyan shilling" },
  { value: "KGS", text: "Kyrgyzstani som" },
  { value: "KHR", text: "Cambodian riel" },
  { value: "KMF", text: "Comorian franc" },
  { value: "KPW", text: "North Korean won" },
  { value: "KRW", text: "South Korean won" },
  { value: "KWD", text: "Kuwaiti dinar" },
  { value: "KYD", text: "Cayman Islands dollar" },
  { value: "KZT", text: "Kazakhstani tenge" },
  { value: "LAK", text: "Lao kip" },
  { value: "LBP", text: "Lebanese lira" },
  { value: "LKR", text: "Sri Lankan rupee" },
  { value: "LRD", text: "Liberian dollar" },
  { value: "LSL", text: "Lesotho loti" },
  { value: "LTL", text: "Lithuanian litas" },
  { value: "LVL", text: "Latvian lats" },
  { value: "LYD", text: "Libyan dinar" },
  { value: "MAD", text: "Morovaluean dirham" },
  { value: "MDL", text: "Moldovan leu" },
  { value: "MGA", text: "Malagasy ariary" },
  { value: "MKD", text: "Macedonian denar" },
  { value: "MMK", text: "Myanma kyat" },
  { value: "MNT", text: "Mongolian tugrik" },
  { value: "MOP", text: "Macanese pataca" },
  { value: "MRO", text: "Mauritanian ouguiya" },
  { value: "MUR", text: "Mauritian rupee" },
  { value: "MVR", text: "Maldivian rufiyaa" },
  { value: "MWK", text: "Malawian kwacha" },
  { value: "MXN", text: "Mexican peso" },
  { value: "MYR", text: "Malaysian ringgit" },
  { value: "MZM", text: "Mozambican metical" },
  { value: "NAD", text: "Namibian dollar" },
  { value: "NGN", text: "Nigerian naira" },
  { value: "NIO", text: "Nicaraguan c\u00f3rdoba" },
  { value: "NOK", text: "Norwegian krone" },
  { value: "NPR", text: "Nepalese rupee" },
  { value: "NZD", text: "New Zealand dollar" },
  { value: "OMR", text: "Omani rial" },
  { value: "PAB", text: "Panamanian balboa" },
  { value: "PEN", text: "Peruvian nuevo sol" },
  { value: "PGK", text: "Papua New Guinean kina" },
  { value: "PHP", text: "Philippine peso" },
  { value: "PKR", text: "Pakistani rupee" },
  { value: "PLN", text: "Polish zloty" },
  { value: "PYG", text: "Paraguayan guarani" },
  { value: "QAR", text: "Qatari riyal" },
  { value: "RON", text: "Romanian leu" },
  { value: "RSD", text: "Serbian dinar" },
  { value: "RUB", text: "Russian ruble" },
  { value: "SAR", text: "Saudi riyal" },
  { value: "SBD", text: "Solomon Islands dollar" },
  { value: "SCR", text: "Seychellois rupee" },
  { value: "SDG", text: "Sudanese pound" },
  { value: "SEK", text: "Swedish krona" },
  { value: "SGD", text: "Singapore dollar" },
  { value: "SHP", text: "Saint Helena pound" },
  { value: "SLL", text: "Sierra Leonean leone" },
  { value: "SOS", text: "Somali shilling" },
  { value: "SRD", text: "Suritextse dollar" },
  { value: "SYP", text: "Syrian pound" },
  { value: "SZL", text: "Swazi lilangeni" },
  { value: "THB", text: "Thai baht" },
  { value: "TJS", text: "Tajikistani somoni" },
  { value: "TMT", text: "Turkmen manat" },
  { value: "TND", text: "Tunisian dinar" },
  { value: "TRY", text: "Turkish new lira" },
  { value: "TTD", text: "Trinidad and Tobago dollar" },
  { value: "TWD", text: "New Taiwan dollar" },
  { value: "TZS", text: "Tanzanian shilling" },
  { value: "UAH", text: "Ukrainian hryvnia" },
  { value: "UGX", text: "Ugandan shilling" },
  { value: "USD", text: "United States dollar" },
  { value: "UYU", text: "Uruguayan peso" },
  { value: "UZS", text: "Uzbekistani som" },
  { value: "VEB", text: "Venezuelan bolivar" },
  { value: "VND", text: "Viettextse dong" },
  { value: "VUV", text: "Vanuatu vatu" },
  { value: "WST", text: "Samoan tala" },
  { value: "XAF", text: "Central African CFA franc" },
  { value: "XCD", text: "East Caribbean dollar" },
  { value: "XDR", text: "Special Drawing Rights" },
  { value: "XOF", text: "West African CFA franc" },
  { value: "XPF", text: "CFP franc" },
  { value: "YER", text: "Yemeni rial" },
  { value: "ZAR", text: "South African rand" },
  { value: "ZMK", text: "Zambian kwacha" },
  { value: "ZWR", text: "Zimbabwean dollar" },
];
